# Generated by Django 4.2.24 on 2025-09-16 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="forumpost",
            name="teaching_class",
            field=models.ForeignKey(
                blank=True,
                help_text="学生发帖时自动关联其所在教学班，用于权限控制",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.teachingclass",
                verbose_name="关联教学班",
            ),
        ),
        migrations.AddField(
            model_name="forumpost",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("public", "完全开放"),
                    ("class_only", "教学班内可见"),
                    ("teacher_only", "私信给教师"),
                ],
                default="public",
                help_text="完全开放：所有注册用户可见；教学班内可见：同教学班学生和任课教师可见；私信给教师：仅作者和任课教师可见",
                max_length=20,
                verbose_name="可见性",
            ),
        ),
    ]
