# Generated by Django 4.2.24 on 2025-09-16 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_forumpost_teaching_class_forumpost_visibility"),
    ]

    operations = [
        migrations.CreateModel(
            name='PostReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_replies_count', models.PositiveIntegerField(default=0, help_text='用户最后一次查看该帖子时的回复总数', verbose_name='已读回复数量')),
                ('last_read_at', models.DateTimeField(auto_now=True, verbose_name='最后阅读时间')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.forumpost', verbose_name='帖子')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '帖子阅读状态',
                'verbose_name_plural': '帖子阅读状态',
            },
        ),
        migrations.AddConstraint(
            model_name='postreadstatus',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='unique_user_post_read_status'),
        ),
    ]
