# Generated by Django 4.2.24 on 2025-09-17 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_assignment_question_questionscore_studentsubmission_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentsubmission",
            name="is_submitted",
            field=models.BooleanField(
                default=True,
                help_text="False表示草稿状态，True表示正式提交",
                verbose_name="是否正式提交",
            ),
        ),
    ]
